### ISSUE TITLE
HELP!  When the lrucache will free the resource ??

### ISSUE THREAD

**Issue by thomaschiao** [openresty/lua-resty-lrucache#10]
When I reload nginx, lrucache how to free memory ?

**Comment by agentzh** [comment]
@thomaschiao It's subject to the Lua garbage collector. Upon nginx HUP reload, the old Lua VM is destroyed, so your lrucache object will certainly be destroyed too. But it might get collected sooner depending on where and whether you anchor your lrucache instances.

**Comment by thomaschiao** [comment]
Thank you.
But in my use case:  
I use lrucache in init.lua. After reload nginx, the memory did not be freed.

**Comment by agentzh** [comment]
@thomaschiao I have no idea what you mean by "init.lua".

**Comment by agentzh** [comment]
@thomaschiao Try providing a minimal and standalone example that can demonstrate your problem to save communication overhead.

**Comment by thomaschiao** [comment]
Sorry, I think I misunderstood the system status.
I use "Top" to monitor the nginx status. I found that the memory is increased after nginx reload.
Today  I tried it again and again. Then I found the memory will decrease after a period time.
Thank you for your helps.

Nice day!!

**Comment by agentzh** [comment]
@thomaschiao Yeah, system memory usage report can be hairy due to its complexity. Glad it was a false alarm :)
