### ISSUE TITLE
Question: when does it take effect after cache setting

### ISSUE THREAD

**Issue by wenchma** [openresty/lua-resty-lrucache#15]
**Description**:

After cache was setting, found it needed to wait for few seconds , then the cache takes effect.
This is the normal situation ? or potential issue ?

**Comment by agentzh** [comment]
@wenchma It should takes effect immediately. You can go through the test suite of this probject for tested examples.

**Comment by agentzh** [comment]
@wenchma One caveat is that this library works on the level of nginx worker processes so different worker processes have a separate cache.

**Comment by wenchma** [comment]
@agentzh thanks for your reply , :+1:   I think I need to consider the cache boundary carefully.

**Comment by agentzh** [comment]
@wenchma BTW, such general questions should go to the openresty mailing lists instead:

http://openresty.org/en/community.html

Thanks for your cooperation.
