### ISSUE TITLE
Question: what's the best usage for lua-resty-lrucache?

### ISSUE THREAD

**Issue by netroby** [openresty/lua-resty-lrucache#17]
Caching what is the best practice ? Cache Web page? cache what?
What's the best usage environment?

**Comment by agentzh** [comment]
@netroby You can cache anything you see fit. Just ensure that you will not cache objects that are too large (like mega bytes or even giga bytes).

**Comment by agentzh** [comment]
@netroby BTW, such general questions should go to the openresty-en mailing list instead. The GitHub issues board is for *real* issues.
