### ISSUE TITLE
Can't save false in cache?

### ISSUE THREAD

**Issue by feisuzhu** [openresty/lua-resty-lrucache#19]
`ubuntu@openresty-test:~$ sudo $(which resty) -e 'lrucache = require "resty.lrucache"; c = lrucache.new(10101); c:set("foo", false); print(c:get("foo") == false)'`
`false`

**Comment by feisuzhu** [comment]
https://github.com/openresty/lua-resty-lrucache/blob/master/lib/resty/lrucache.lua#L145

should be `if val ~= nil then`

**Comment by agentzh** [comment]
@feisuzhu Good catch. Will you submit a pull request for it? Thanks!

**Comment by feisuzhu** [comment]
Already merged
