### ISSUE TITLE
key 过期后，再次get返回的数据是"nil0"

### ISSUE THREAD

**Issue by syzh** [openresty/lua-resty-lrucache#21]
lru:set(key, val, 30)
过期后再次get返回nil0
lru:get(key) == nil0

**Comment by syzh** [comment]
看了一下源码解决了，原来过期后会返回nil, oldval

if node.expire >= 0 and node.expire < ngx_now() then
        return nil, val
    end

**Comment by agentzh** [comment]
Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.
