### ISSUE TITLE
about struct type and struct point in lua

### ISSUE THREAD

**Issue by hy05190134** [openresty/lua-resty-lrucache#22]
https://github.com/openresty/lua-resty-lrucache/blob/master/lib/resty/lrucache.lua#L42

why just set "x.next = h" rather than "x.next = h[0]", though the h is the struct point type, but in other function, you just set  "x.next = h[i]", so I am confused with the ffi  struct type and ffi struct point type

**Comment by agentzh** [comment]
@hy05190134 No, it's wrong to use `x.next = h[0]` there. The types are different.

**Comment by hy05190134** [comment]
@agentzh  but why just use  h[0].next = h[1], since the type of h is different with the type of h[1]

**Comment by agentzh** [comment]
Which line of code are you referencing?

**Comment by hy05190134** [comment]
@agentzh  https://github.com/openresty/lua-resty-lrucache/blob/master/lib/resty/lrucache.lua#L62, when i = 1,  it will execute  q[0].next = q[1]

**Comment by agentzh** [comment]
@hy05190134 Good catch. It should be fixed using the following patch:

```diff
diff --git a/lib/resty/lrucache.lua b/lib/resty/lrucache.lua
index f5cb108..ce2baa9 100644
--- a/lib/resty/lrucache.lua
+++ b/lib/resty/lrucache.lua
@@ -58,7 +58,7 @@ local function queue_init(size)
     else
         local prev = q[0]
         for i = 1, size do
-          local e = q[i]
+          local e = q + i
           prev.next = e
           e.prev = prev
           prev = e
```

The old form still works maybe due to LuaJIT's magic.

**Comment by agentzh** [comment]
Committed the patch.
