### ISSUE TITLE
Dose the value support table or any of lua data type

### ISSUE THREAD

**Issue by jiansongjay** [openresty/lua-resty-lrucache#24]
ngx shared dict can only support string,num,boolen,not support table.
Dose Lrucache support table or any lua data type.

**Comment by agentzh** [comment]
@jiansongjay I think it's already officially documented:

https://github.com/openresty/lua-resty-lrucache#description

To quote,

> The LRU cache resides completely in the Lua VM and is subject to Lua GC. So do not expect it to get shared across the OS process boundary. The upside is that you can cache arbitrary complex Lua values (like deep nested Lua tables) without the overhead of serialization (as with ngx_lua's shared dictionary API).

Please read the documentation carefully.
