### ISSUE TITLE
SET key does not throw error, but never get a match on GET

### ISSUE THREAD

**Issue by doktoroblivion** [openresty/lua-resty-lrucache#31]
I am using the lrucache trying to use a key that is the JWT (token) passed in, so there is no question of the caller I am processing the request for.  The value is a JSON table with paths, etc...  Upon the set operation with (key, value), no error is thrown, but on subsequent get calls I never get a match, a nil always comes back which makes no sense to me unless some kind of key truncation is occurring.
So my question is, is there some unknown size for the **key** that can be used/passed-in, does the **key** support **special characters** that can exist in a JWT, and are there any other undocumented restrictions?
I think the actual question is probably one of scoping the LRUCache variable, since if I am not mistaken globals are not maintained across separate calls.  In that case if I am keeping all my LUA logic in one lua module, should that be kept in NGINX and reference in LUA using ngx.var..., or something else?

**Comment by spacewander** [comment]
@doktoroblivion 
Did you specify enough space to hold the keys? The `new` method have a `max_item` option:
https://github.com/openresty/lua-resty-lrucache#new

AFAIK, there is not special characters limitation to the key, because the key is Lua string.

Could you submit a minimal reproduce case to us?

**Comment by doktoroblivion** [comment]
Does the cache have to be scoped outside LUA?  That is, do I have to define a variable in nginx instead of just in lua to hold the cache?  The symptom I am seeing could be explained if the cache is getting created each time the lua code is called, which I thought I saw others saying was the issue, not sure(?)

**Comment by doktoroblivion** [comment]
lua_code_cache is on by default, however, even if I use the directive, the cache get's created each time.  Here is some code and output.  Below is part of my location:
```
      lua_code_cache on;

      access_by_lua_file /etc/api-gateway/scripts/lua/analytics_access.lua;
```
Here is the beginning of that lua mod:
```
local curl = require 'resty.jwt'
local http = require "resty.http"
local json = require "cjson"

local json_safe = require "cjson.safe"
local jwt       = require 'resty.jwt'
local lrucache  = require "resty.lrucache.pureffi"
local ssl = require "ngx.ssl";

local headers = ngx.req.get_headers();

-- max LRU cached items
local max_items = 10000;
-- Create a LRU cache if one does not exist
local LRUcache, err = lrucache.new(max_items);
if LRUcache == nil then
    if err ~= nil then
        -- TODO: not sure we should fail because of this, could be a system/VM resource issue
        ngx.log(ngx.WARN, 'Caching error: received error creating LRU cache: ', err);
        ngx.log(ngx.WARN, '*** Analytics Proxy in performance degradation mode ***');
    end
else
    ngx.log(ngx.DEBUG, '*** LRUCache successfully created ***');
end
```
And here a multiple invocations of a call hitting that location:
```
2018/03/08 13:08:37 [debug] 30#0: *10 [lua] analytics_access.lua:23: *** LRUCache successfully created ***
...
2018/03/08 13:08:46 [info] 31#0: *14 client closed connection while SSL handshaking, client: 172.16.93.1, server: 0.0.0.0:8084
2018/03/08 13:08:52 [info] 31#0: *15 client closed connection while SSL handshaking, client: 172.16.93.1, server: 0.0.0.0:8084
2018/03/08 13:08:55 [debug] 31#0: *16 [lua] analytics_access.lua:23: *** LRUCache successfully created ***
```

**Comment by doktoroblivion** [comment]
So in the above code I thought I should do this instead of following the example
```
local LRUcache;
if LRUcache == nil then
    LRUcache, err = lrucache.new(max_items);
    if LRUcache == nil and err ~= nil then
        -- TODO: not sure we should fail because of this, could be a system/VM resource issue
    end
else
    ngx.log(ngx.DEBUG, '*** LRUCache exists ***');
end
```
But that didn't seem to matter.

**Comment by doktoroblivion** [comment]
I think this says it all from the lua-nginx-module, which means my lrucache storage must not be local within the lua coroutine
"Lua-nginx-module uses one-coroutine-per-request request handling model, i.e. for each incoming request, lua-nginx-module creates a coroutine to run user code to process the request, and the coroutine will be destroyed when the request handling process is done. Every coroutine has its own independent global environment, which inherits shared read-only common data. So any global values injected by the user code won’t affect other request’s processing, and will be freed when request handling is done. You can imagine that user code is running in a ‘sandbox’, which shares the same lifecycle with the request itself. By this way, lua-nginx-module can prevent memory-leak caused by abusing uses of global values in user code, hence improve robustness."

**Comment by spacewander** [comment]
@doktoroblivion 
You're right. It is what the example in the documentation does:
https://github.com/openresty/lua-resty-lrucache#synopsis
