### ISSUE TITLE
failed to load the 'resty.lrucache' module，Is there an error in the installation manual?

### ISSUE THREAD

**Issue by 919927181** [openresty/lua-resty-lrucache#63]
nginx: [alert] failed to load the 'resty.lrucache' module

You can install this module with the following command to resolve the above problem.

```
cd lua-resty-core
sudo make install LUA_LIB_DIR=/usr/local/share/lua/5.1
```

cd lua-resty-core  Should be cd lua-resty-lrucache

**Comment by zhuizhuhaomeng** [comment]
fixed https://github.com/openresty/lua-resty-lrucache/commit/82b5ab467aa46495db09499725eb87d4a7c1bc1c
